[package]
name = "lapi-launcher"
version = "1.0.0"
edition = "2024"
description = "A terminal application launcher for Linux"
license = "MIT"
repository = "https://github.com/Lubi-git/lapi-launcher"

[dependencies]
anyhow = "1"
crossterm = "0.29"
freedesktop-desktop-entry = { version = "0.8.3", default-features = false }
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "webp", "ico"] }
nucleo-matcher = "0.3"
ratatui = { version = "0.30", default-features = false, features = ["crossterm"] }
ratatui-image = { version = "11.0.8", default-features = false, features = ["crossterm"] }
serde = { version = "1", features = ["derive"] }
toml = "1.1"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
